### ISSUE TITLE
Couldn't open CUDA library libcudnn.so

### ISSUE THREAD

**Issue by AndreaIncertiDelmonte** [ra9hur/Udacity-SDC-Docker-GPU#1]
Hi ra9hur,

I'm running your image on Ubuntu 14.04 and Tensorflow can't load cudann shared object. 
`I tensorflow/stream_executor/dso_loader.cc:119] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64`

This will cause the following error:
`tensorflow/stream_executor/cuda/cuda_dnn.cc:221] Check failed: s.ok() could not find cudnnCreate in cudnn DSO; dlerror: /opt/conda/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: cudnnCreate` and the notebook will die.

I also tried to add more libraries to LD_LIBRARY_PATH as suggested here [https://www.tensorflow.org/get_started/os_setup#docker_installation](url) and got the same result

Did you got errors like these?

Andrea

**Comment by ra9hur** [comment]
Hi Andrea,

Thanks for raising this.
Symbolic link to "libcudnn.so" in /usr/local/cuda/lib64 is missing. This should have been taken care during CUDA/CUDNN installation.

Have separately included this link and changes are made to the Dockerfile.

Please check, if it works now.

**Comment by AndreaIncertiDelmonte** [comment]
Hi ra9hur,

it works ;) 

Tnks for your help
